name: make-plugin-release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:

  create-plugin-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Tag metadata file
        run: sed -i -E "s/^version=v{0,1}[0-9]+\.[0-9]\.{0,1}[0-9]*/version=${{github.ref_name}}/g" ./plugin/metadata.txt
      - name: Create zip file
        run: |
          pip install PyQt5
          cd ./plugin
          make zip
      - name: Automatic push changes
        run: |
          git config --global user.name ${{github.actor}}
          git stash
          git checkout main
          git stash apply
          git add ./plugin/metadata.txt
          git commit -m "Commit from GitHub Actions (create-plugin-zip)"
          git push
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./plugin/recartDGT.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
